# https://travis-ci.org/DavidPal/bibliography
language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev # 3.5 development branch
  - 3.6-dev # 3.6 development branch
  - nightly # currently points to 3.7-dev
  # PyPy versions
  - pypy3 # Pypy3 2.4.0
  - pypy-5.3.1

install:
  - "pip install unittest2 nose coveralls pytest"

script:
  - "py.test --verbose"
