# https://travis-ci.org/DavidPal/bibliography
dist: bionic
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # currently points to 3.7-dev
  - "pypy3"    # Pypy3 2.4.0

install:
  - "pip install unittest2 nose coveralls pytest"

script:
  - "py.test --verbose"
