# https://travis-ci.org/DavidPal/bibliography
dist: bionic
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install unittest2 nose coveralls pytest pylint"

script:
  - "pytest --verbose"
  - "pylint --version"
  - "pylint --disable=superfluous-parens,redefined-builtin,useless-object-inheritance  bibliography.py"
